version: "3"

services:
  web:
    image: euclid1990/simple-python-app
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "6969:5000"
    networks:
      - webnet
    volumes:
      - .:/code
    command: ["./wait-for-it.sh", "redis:6379", "--", "python", "app.py"]

  redis:
    image: "redis:3.0.7"
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9696:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:
